# -*- coding: utf-8 -*-
"""tech_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kGJqhGyr8Voe8cyHhG94CGSPxdar864
"""

import yfinance as yf
import pandas as pd
from ta.momentum import RSIIndicator
from ta.trend import MACD, SMAIndicator
from ta.volatility import BollingerBands

from datetime import date, timedelta
from ta.volatility import BollingerBands

tickers = ['GOOGL', 'META', 'NVDA', 'TSLA']

all_data = []

start_date = date.today() - timedelta(days=365*5.2)

for ticker in tickers:
    # 1. Download data
    df = yf.download(ticker, start = start_date)

    # 2. FLATTEN THE MULTIINDEX
    # This turns the nested 'Price/Ticker' columns into simple single columns
    df.columns = df.columns.get_level_values(0)

    # 3. Add the Ticker column
    df['Ticker'] = ticker

    # Now df['Close'] is a standard Series, and your indicators will work perfectly
    close_prices = df['Close']

    # --- Your existing indicator logic ---
    df['RSI'] = RSIIndicator(close=close_prices, window=14).rsi()
    macd = MACD(close=close_prices)
    df['MACD'] = macd.macd()
    df['MACD_signal'] = macd.macd_signal()

    # Initialize Bollinger Bands Indicator
    indicator_bb = BollingerBands(close=df['Close'], window=20, window_dev=2)

    # Add bands to your dataframe
    df['BB_High'] = indicator_bb.bollinger_hband()
    df['BB_Low'] = indicator_bb.bollinger_lband()
    df['BB_Mid'] = indicator_bb.bollinger_mavg() # The SMA 20

    # 4. Reset index so 'Date' becomes a regular column
    all_data.append(df.reset_index())

# 5. Combine everything into one long table
final_df = pd.concat(all_data, ignore_index=True)

# Ensure columns are a single level index after concatenation
# The kernel state output and KeyError suggest that `final_df` might have MultiIndex columns after concat.
# For example, ('Price', 'Close') or ('Price', 'Ticker').
# This line flattens the columns by dropping the top level.
# It's safer to ensure this after concat as `yf.download` and `pd.concat` can sometimes lead to MultiIndex.
if isinstance(final_df.columns, pd.MultiIndex):
    final_df.columns = final_df.columns.droplevel(0)

# Filter out rows with any NaN values
final_df = final_df.dropna()

final_df

import numpy as np

# Create a function to apply to each ticker group
def add_signals(df):
    # 1. MACD Crossover Signals
    # Buy when MACD crosses above Signal; Sell when it crosses below
    df['MACD_Action'] = 'Hold'
    df.loc[(df['MACD'] > df['MACD_signal']) & (df['MACD'].shift(1) <= df['MACD_signal'].shift(1)), 'MACD_Action'] = 'Buy'
    df.loc[(df['MACD'] < df['MACD_signal']) & (df['MACD'].shift(1) >= df['MACD_signal'].shift(1)), 'MACD_Action'] = 'Sell'

    # 2. RSI Threshold Signals
    df['RSI_Action'] = 'Hold'
    df.loc[df['RSI'] < 30, 'RSI_Action'] = 'Buy'
    df.loc[df['RSI'] > 70, 'RSI_Action'] = 'Sell'

    # 3. Bollinger Band Signals (Mean Reversion Strategy)
    df['BB_Action'] = 'Hold'
    # Buy when price closes below the Lower Band
    df.loc[df['Close'] <= df['BB_Low'], 'BB_Action'] = 'Buy'
    # Sell when price closes above the Upper Band
    df.loc[df['Close'] >= df['BB_High'], 'BB_Action'] = 'Sell'

    return df

# Apply the signals to each ticker separately
final_df = final_df.groupby('Ticker', group_keys=False).apply(add_signals)

# Display the latest signals for each ticker
#print(final_df.groupby('Ticker').tail(1)[['Date', 'Ticker', 'Close', 'MACD_Action', 'RSI_Action', 'SMA_Action']])

final_df

import google.generativeai as genai
import os

# 1. Robust API Key loading
try:
    from google.colab import userdata
    api_key = userdata.get('GEMINI_API_KEY')
except Exception:
    api_key = os.getenv("GEMINI_API_KEY")

genai.configure(api_key=api_key)

import pandas as pd
import google.generativeai as genai

def get_ticker_comments(df):
    # 1. Identify unique tickers in the dataset
    tickers = df['Ticker'].unique()

    # List to store our final results
    results = []

    # Using the latest stable model for 2026
    model = genai.GenerativeModel('gemini-2.5-flash')

    print(f"Starting analysis for {len(tickers)} tickers...")

    for ticker in tickers:
        # 2. Get the latest data point for THIS specific ticker
        ticker_data = df[df['Ticker'] == ticker].iloc[-1]

        # Prepare a focused prompt for a single ticker
        prompt = f"""
        You are a Senior Quantitative Analyst. Analyze the technical state of {ticker}:
        - Price: ${ticker_data['Close']:.2f}
        - RSI: {ticker_data['RSI']:.2f} ({ticker_data['RSI_Action']})
        - MACD: {ticker_data['MACD']:.3f} (Signal: {ticker_data['MACD_signal']:.3f})
        - MACD Action: {ticker_data['MACD_Action']}
        - BB High: {ticker_data['BB_High']}
        - BB Mid: {ticker_data['BB_Mid']}
        - BB Low: {ticker_data['BB_Low']}

        Provide a 2-sentence technical summary within 100 words.
        """

        try:
            # 3. Generate comment for this ticker
            response = model.generate_content(prompt)
            comment = response.text.strip()

            # Append to results list
            results.append({
                'Ticker': ticker,
                'Comment': comment
            })
            print(f"Processed: {ticker}")

        except Exception as e:
            print(f"Error analyzing {ticker}: {str(e)}")
            results.append({'Ticker': ticker, 'Comment': "Analysis failed."})

    # 4. Convert the results list into a new DataFrame (Table)
    analysis_table = pd.DataFrame(results)
    return analysis_table

# Execute the analysis
analysis_df = get_ticker_comments(final_df)

analysis_df

import os
import json
import gspread

# 1. Google Sheets Auth
# This converts the secret string back into a dictionary
creds_dict = json.loads(os.getenv("GSPREAD_SERVICE_ACCOUNT"))
gc = gspread.service_account_from_dict(creds_dict)
sh = gc.open_by_key('1cRfD5aB31by5LHX5mAyr2gdw5tUvcjREybpUrFxVgSE')

# Write to Google Sheets
def update_sheet(df, sheet_name):
    worksheet = sh.worksheet(sheet_name)
    worksheet.clear()
    # Adding header and values
    worksheet.update([df.columns.values.tolist()] + df.astype(str).values.tolist())

update_sheet(final_df, "indicators")
update_sheet(analysis_df, "tech_analysis")
